from django.conf.urls import include, url
from . import views
from . import viewReporteProductos,viewModificarCliente,viewAsignarCaja,viewListadoProductos,viewBusquedaMercaderia,viewPrecios,viewCliente, viewIngresoMercaPorProveedor, viewCompra, viewPuntodeVenta, viewTrasladoMercaderia, viewCierreCaja, viewAnularVenta, viewInventario, viewPromocion,viewEmpleados, viewCotizacion
from . import viewTablas
urlpatterns=[
#urls para loguear
url(r'^$','django.contrib.auth.views.login',
{'template_name':'kadoshapp/login.html'}, name='login'),

url(r'^cerrar/$','django.contrib.auth.views.logout_then_login',name='logout'),
url(r'^index/kadosh/', views.ingreso_mercaderia, name='ingreso_mercaderia'),
url(r'^Acceso/Denegado/', views.denegado, name='denegado'),
url(r'^ingreso/cliente/$', viewCliente.registro_cliente, name='registroCliente'),
url(r'^modificar/cliente/$', viewModificarCliente.mod_cliente, name='modcliente'),
url(r'^ingreso/MercaderiaPoProveedor/$',viewIngresoMercaPorProveedor.ingresodemercaderiaporProveedor, name='IngresoMercaPorProveedor'),
url(r'^ingreso/Compra/$', viewCompra.Compra, name='Compra'),
url(r'^Realizacion/Venta/$', viewPuntodeVenta.PuntoDeVenta, name='PuntoDeVenta'),
url(r'^Traslado/Mercaderia/$', viewTrasladoMercaderia.TrasladoMercaderia, name='TrasladoMerca'),
url(r'^Cierre/Caja/$', viewCierreCaja.CierreDeCaja, name='CierreDeCaja'),
url(r'^Venta/Anular/$', viewAnularVenta.AnularVenta, name='AnularVenta'),
url(r'^Inventario/Nuevo/$', viewInventario.Inventario, name='Inventario'),
url(r'^Promocion/Nuevo/$', viewPromocion.Promocion, name='Promocion'),
url(r'^Buscar/Producto/$', viewPuntodeVenta.BuscarProducto, name='BusquedaProd'),
url(r'^Buscar/Producto/Precio/$', viewPrecios.BuscarProducto, name='BusquedaProdPrecio'),
url(r'^Buscar/Precio/$', viewPrecios.BuscarPrecio, name='BusquedaPrecio'),
url(r'^Buscar/Venta/$', viewAnularVenta.BuscarVenta, name='BusquedaVenta'),
url(r'^Buscar/ProductoCaracteristicas/$', viewPuntodeVenta.BuscarProductoCaracteristicas, name='BusquedaProdCar'),
url(r'^Buscar/ImagenProducto/$', viewPuntodeVenta.BuscarProductoImagenPrincipal, name='BusquedaProdImg'),
url(r'^Anulacion/Venta/$', viewAnularVenta.AnulacionVenta, name='AnulacionVenta'),
url(r'^Empleados/Categoria/$', viewEmpleados.Empleados, name='Empleados'),
url(r'^Buscar/Empleados/$', viewEmpleados.BuscarEmpleados, name='BusquedaEmpleados'),
url(r'^Buscar/Cierre/$', viewCierreCaja.BuscarCaja, name='BusquedaCaja'),
url(r'^Buscar/ProductosInventario/$', viewInventario.BuscarProducto, name='BusquedaProductoInv'),
url(r'^Cambiar/Puesto/$', viewEmpleados.CambiarPuestoEmpleado, name='PuestoEmpleados'),
url(r'^Asignar/Precio/$', viewPrecios.Precios, name='Precios'),
url(r'^Mercaderia/Busqueda/$', viewBusquedaMercaderia.BusquedaMerca, name='BusquedaMercaderia'),
url(r'^Productos/Listado/$', viewListadoProductos.Listado, name='ListadoProductos'),
url(r'^Registrar/Gasto/$', viewAsignarCaja.RegistrarGasto, name='RegitrarGasto'),
url(r'^Guardar/Venta/$', viewPuntodeVenta.GuardarVenta, name='GuardarVenta'),
url(r'^Guardar/Precio/$', viewPrecios.GuardarPrecio, name='GuardarPrecio'),
url(r'^Buscar/TodosProductosCaracteristicas/$', viewListadoProductos.BuscarProductoCaracteristicasExtra, name='BuscarListadoProductos'),
url(r'^Buscar/TodosProductosCaracteristicasExtra/$', viewListadoProductos.BuscarProductoCaracteristicasExtra, name='BuscarListadoProductos'),
url(r'^Buscar/TodosProductosExtra/$', viewListadoProductos.BuscarProductoExtra, name='BuscarListadoProductos'),
url(r'^Guardar/Venta/$', viewPuntodeVenta.GuardarVenta, name='GuardarVenta'),
#url(r'^reporte_personas_excel/$',viewReportePersonas.ReportePersonas.as_view(), name="reporte_personas_excel"),
#url(r'^Reporte/Personas/', viewTablas.persona_lista, name='Rpersonas'),
url(r'^cotizaciones/$',viewCotizacion.ReporteCotizacion.as_view(), name="reporte_cotizacion_excel"),
url(r'^reporte_productos_excel/$',viewReporteProductos.ReporteProductos.as_view(), name="reporte_productos_excel"),
url(r'^Reporte/Productos/', viewTablas.productos_lista, name='Rproductos'),
]
